#server:
#  port: 9090
#  error:
#    include-message: always
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    url: jdbc:mysql://containers-us-west-35.railway.app:7833/railway
#    password: WtRwCc1xE8vwphMxEoO5
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  port: 9090
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/manageequipment
    password: 0392338494
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
